/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Submissions */
        get: operations["list_submissions_api_submissions_get"];
        put?: never;
        /** Create Submission */
        post: operations["create_submission_api_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Submissions Bulk */
        post: operations["create_submissions_bulk_api_submissions_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start
         * @description Flip every loaded row to processing and schedule extraction.
         *
         *     Defined `async` so `asyncio.create_task(...)` inside `_schedule_processing`
         *     targets the main event loop. With a sync handler in FastAPI's threadpool
         *     the scheduled tasks would race against the request's own row locks and
         *     deadlock. The handler returns immediately; the queued tasks run after
         *     the request's session commits and releases its locks.
         */
        post: operations["start_api_submissions_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission */
        get: operations["get_submission_api_submissions__submission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{submission_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image */
        get: operations["get_image_api_submissions__submission_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{submission_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Decision */
        post: operations["create_decision_api_submissions__submission_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{submission_id}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Override */
        post: operations["create_override_api_submissions__submission_id__overrides_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{submission_id}/overrides/{field}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Override */
        delete: operations["delete_override_api_submissions__submission_id__overrides__field__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Demo */
        post: operations["reset_demo_api_admin_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminResetIn */
        AdminResetIn: {
            /** Confirm */
            confirm: boolean;
        };
        /** AdminResetOut */
        AdminResetOut: {
            /** Deleted Submissions */
            deleted_submissions: number;
            /** Restored Fixtures */
            restored_fixtures: number;
        };
        /** Body_create_submission_api_submissions_post */
        Body_create_submission_api_submissions_post: {
            /** Image */
            image?: string | null;
            /** Expected Values */
            expected_values?: string | null;
        };
        /** Body_create_submissions_bulk_api_submissions_bulk_post */
        Body_create_submissions_bulk_api_submissions_bulk_post: {
            /** Csv */
            csv?: string | null;
            /** Images */
            images?: string[] | null;
        };
        /** BulkCreateOut */
        BulkCreateOut: {
            /** Created */
            created: components["schemas"]["SubmissionCreateOut"][];
            /** Errors */
            errors: components["schemas"]["BulkErrorOut"][];
        };
        /** BulkErrorOut */
        BulkErrorOut: {
            /**
             * Row
             * @description 1-based CSV row number (excluding header). None for batch-level errors.
             */
            row?: number | null;
            /** Filename */
            filename?: string | null;
            /** Reason */
            reason: string;
        };
        /** DecisionIn */
        DecisionIn: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Comment */
            comment?: string | null;
            /** Rejection Field Ids */
            rejection_field_ids?: string[] | null;
        };
        /** DecisionOut */
        DecisionOut: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Comment */
            comment?: string | null;
            /** Rejection Field Ids */
            rejection_field_ids?: string[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DiffToken */
        DiffToken: {
            /** Text */
            text: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "equal" | "added" | "removed";
        };
        /**
         * ExpectedValues
         * @description The expected-values payload stored on a submission (JSONB column).
         *
         *     Cross-field rule: if `is_imported` is true, `country_of_origin` must be a
         *     non-empty string. Validated at the API boundary; the DB column is JSONB and
         *     does not enforce shape.
         */
        ExpectedValues: {
            /** Brand */
            brand: string;
            /** Class Type */
            class_type: string;
            /** Alcohol Content */
            alcohol_content: number;
            /** Net Contents */
            net_contents: string;
            /** Producer Name */
            producer_name: string;
            /** Producer Address */
            producer_address: string;
            /** Is Imported */
            is_imported: boolean;
            /** Country Of Origin */
            country_of_origin?: string | null;
        };
        /** ExtractionOut */
        ExtractionOut: {
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms?: number | null;
            tokens: components["schemas"]["ExtractionTokens"];
            /** Error */
            error?: string | null;
        };
        /** ExtractionTokens */
        ExtractionTokens: {
            /** Input */
            input?: number | null;
            /** Output */
            output?: number | null;
        };
        /** FieldGroupOut */
        FieldGroupOut: {
            /**
             * Name
             * @enum {string}
             */
            name: "Identity" | "Producer" | "Quantitative" | "Origin" | "Government Warning";
            /** Fields */
            fields: components["schemas"]["FieldRowOut"][];
        };
        /** FieldRowOut */
        FieldRowOut: {
            /**
             * Id
             * Format: uuid
             * @description comparisons.id — referenced from rejection_field_ids.
             */
            id: string;
            /** Field */
            field: string;
            /** Extracted Value */
            extracted_value?: string | null;
            /** Expected Value */
            expected_value?: string | null;
            /**
             * Model Verdict
             * @enum {string}
             */
            model_verdict: "pass" | "fail" | "not_applicable";
            /**
             * Effective Verdict
             * @enum {string}
             */
            effective_verdict: "pass" | "fail" | "not_applicable";
            /** Rule */
            rule: string;
            /** Reason */
            reason?: string | null;
            /** Confidence */
            confidence?: ("hi" | "med" | "low") | null;
            /** Diff Extracted */
            diff_extracted?: components["schemas"]["DiffToken"][] | null;
            /** Diff Expected */
            diff_expected?: components["schemas"]["DiffToken"][] | null;
            override?: components["schemas"]["OverrideOut"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OverrideIn */
        OverrideIn: {
            /** Field */
            field: string;
            /**
             * Override Verdict
             * @enum {string}
             */
            override_verdict: "pass" | "fail";
            /**
             * Comment
             * @default
             */
            comment: string;
        };
        /** OverrideOut */
        OverrideOut: {
            /** Field */
            field: string;
            /**
             * Original Verdict
             * @enum {string}
             */
            original_verdict: "pass" | "fail" | "not_applicable";
            /**
             * Override Verdict
             * @enum {string}
             */
            override_verdict: "pass" | "fail";
            /** Comment */
            comment: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ReviewOut */
        ReviewOut: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Comment */
            comment?: string | null;
            /** Rejection Field Ids */
            rejection_field_ids?: string[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StartOut */
        StartOut: {
            /** Scheduled */
            scheduled: number;
            /** Submission Ids */
            submission_ids: string[];
        };
        /** SubmissionCreateOut */
        SubmissionCreateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "loaded" | "processing" | "ready_for_review" | "approved" | "rejected" | "extraction_failed";
        };
        /** SubmissionDetailOut */
        SubmissionDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "loaded" | "processing" | "ready_for_review" | "approved" | "rejected" | "extraction_failed";
            /** Is Fixture */
            is_fixture: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Image Url */
            image_url: string;
            expected_values: components["schemas"]["ExpectedValues"];
            extraction?: components["schemas"]["ExtractionOut"] | null;
            /** Groups */
            groups?: components["schemas"]["FieldGroupOut"][];
            review?: components["schemas"]["ReviewOut"] | null;
        };
        /** SubmissionListItem */
        SubmissionListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "loaded" | "processing" | "ready_for_review" | "approved" | "rejected" | "extraction_failed";
            /**
             * Brand
             * @description Derived from expected_values.brand for display.
             */
            brand: string;
            /** Is Fixture */
            is_fixture: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Thumbnail Url */
            thumbnail_url: string;
            /** Has Extraction Error */
            has_extraction_error: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_submissions_api_submissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionListItem"][];
                };
            };
        };
    };
    create_submission_api_submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_submission_api_submissions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionCreateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_submissions_bulk_api_submissions_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_submissions_bulk_api_submissions_bulk_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkCreateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_submissions_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartOut"];
                };
            };
        };
    };
    get_submission_api_submissions__submission_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_api_submissions__submission_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_decision_api_submissions__submission_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_override_api_submissions__submission_id__overrides_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_override_api_submissions__submission_id__overrides__field__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
                field: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_demo_api_admin_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminResetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminResetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
